# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:05:24+00:00

from __future__ import annotations

from pydantic import BaseModel


class Country(BaseModel):
    value: str


class NewValue(BaseModel):
    value: str


class PostalCode(BaseModel):
    value: str


class Public(BaseModel):
    country: Country
    postalCode: PostalCode


class Public1(BaseModel):
    newValue: NewValue


class CreatenewsessionRequest(BaseModel):
    public: Public


class EditsessionRequest(BaseModel):
    public: Public1


class ModifysessiongettingspecificparametersRequest(BaseModel):
    public: Public
